### ISSUE TITLE
00:00-02:00 "current" gas & energy price is missing

### ISSUE THREAD

**Issue by xanderificnl** [klaasnicolaas/python-easyenergy#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/klaasnicolaas/python-easyenergy/assets/8600870/fa5b576f-dc94-4c99-98ad-24ebec8e9c48)

### Expected Behavior

For 00:00-02:00 prices to be visible

### Steps To Reproduce

1. environment below
2. config:
```yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
tts:
  - platform: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt_discoverystream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  publish_discovery: true
powercalc:
template:
  - sensor:
    - name: "EasyEnergy - Current energy price"
      unit_of_measurement: "€/kWh"
      # As of 03-02-2023 / https://www.easyenergy.com/nl/energietarieven
      state: >
        {% set minieme_opslag     = (2.178  / 100) %}
        {% set energie_belasting  = (15.245 / 100) %}
        {% set stroom_vergroening = (0.908  / 100) %}
        {% set current_hour_price = states('sensor.easyenergy_today_energy_usage_current_hour_price') | default(0) | float %}
        {{ (current_hour_price + minieme_opslag + energie_belasting + stroom_vergroening) | round(6) }}
    - name: "EasyEnergy - Current gas price"
      unit_of_measurement: "€/m³"
      # As of 03-02-2023 / https://www.easyenergy.com/nl/energietarieven
      state: >
        {% set minieme_opslag     = (10.89  / 100) %}
        {% set energie_belasting  = (59.266 / 100) %}
        {% set regio_toeslag      = (1.903  / 100) %}
        {% set current_hour_price = states('sensor.easyenergy_today_gas_current_hour_price') | default(0) | float %}
        {{ (current_hour_price + minieme_opslag + energie_belasting + regio_toeslag) | round(6) }}
```

### Environment

```Markdown
OS: Fedora CoreOS (38.20230609.3.0)
Container Engine: Podman
Container Image: docker.io/linuxserver/homeassistant:2023.6.2
TZ: UTC
```

### Anything else?

A quick summary

1. A grep for issues shows my template sensors see `sensor.easyenergy_today_energy_usage_current_hour_price` as having a "unknown" value value everyday at 23:00. The log states 22:00 but that's because my TZ is set to UTC but the frontend of HA shows my local time (GMT+1). 

```
2023-07-12 22:00:42.677 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template
``` 

2. I've disabled the EasyEnergy Return sensors since I'm not able to return power to the grid.
3. Just now enabled debugging for the integration and hoping to see more details later tonight/tomorrow morning; just in case we need more data. 
4. Other sensors _do_ register without interruptions so it isn't an HA-wide issue as far as I can tell.

If there's any more details I can provide, please let me know. I'm guessing there's a small bug somewhere, either in my setup or the code, or an interaction thereof; with debugging on we might have more useful data tomorrow.
