### ISSUE TITLE
hass

### ISSUE THREAD

**Issue by xanderificnl** [klaasnicolaas/python-easyenergy#4]
Hi there!

Is there a specific/recommended way of integrating this with homeassistant? 

Thanks,

- Xander

**Comment by klaasnicolaas** [comment]
For that I first have to write an integration, something I'll take the time to do in the coming days because I'm finally on vacation 😅

**Comment by xanderificnl** [comment]
Very cool. Much appreciated.

Geniet van je vakantie!

**Comment by JWMass** [comment]
Hi Klaas,

Good to see some progress on this one, I am really looking forward to the HASS integration. Do you have a rough idea when this will be completed? 

Thanks, Jan Willem

**Comment by klaasnicolaas** [comment]
I'm already well on my way with an integration, I still have to create the entities and then write tests. However, at the moment I am busy finishing some things for study. Probably early February when people can run it as a custom integration and I hope it can be merged into core by the March release.

./Klaas

**Comment by JWMass** [comment]
That sounds perfect to me, switching to easy energy at the end of this month. 

In case you need any form of testing, happy to assist.

**Comment by malosaa** [comment]
Cant wait for this add-on to test it out.
I'm at Easy energy for 4 months (gas only) as energy is for me still cheaper where i am now as i only pay 10€ a month.

@JWMass  be aware that they use higher monthly (voorschot) but its still cheaper than the rest.
They do this because its pre-paid to protect yourself.
This changes after 1 year, when they have your average usage available.
As in 2024 the energie prijs plafond goes away and they will use the consume data from this year.
If you save now you good to go in 2024.

Thanks to @klaasnicolaas his add-on :)

**Comment by klaasnicolaas** [comment]
It's not an add-on but an integration :wink:

Almost everything is ready in core, so the target for the release in March will be achieved. In fact, I will share a zip file with the integration code over the weekend, for those who would like to get started with it.

./Klaas

**Comment by klaasnicolaas** [comment]
For those who would like to test, you can download the zip below and put the files in the custom_components folder, restart HA and then add the integration in the UI.

[easyenergy_v0.1.0.zip](https://github.com/klaasnicolaas/python-easyenergy/files/10527321/easyenergy_v0.1.0.zip)

**Comment by JWMass** [comment]
> 

Thanks, Installed the integration and it's running now, already working perfectly for the energy dashboard :) 👍 

Am I correct that this is not (yet) pulling in the energy pricing per hour itself? I would like to show the hourly rate in an apex chart for today/tomorrow to visualise when it would be the best time to run the high energy consuming devices.  I can see it nows when it's the lowest and when it's the highest rate which is hopeful that the rates are available?

**Comment by klaasnicolaas** [comment]
With the version that comes in core it is not possible to map the prices in an apexchart via the attributes, this method is a workaround that creates a bulk load of data in the state machine and is not accepted in core.

There are ideas to provide better support in core in the future, but we are not there yet. However, with some adjustments in the code you can still retrieve it (like entso-e and nordpool do)

**Comment by JWMass** [comment]
All my sensors are down since yesterday. Seems to have an issue with collection of the data?

![EC504B3C-66A3-4017-A2D3-0A28E1C4E6EF](https://user-images.githubusercontent.com/112503137/215416499-5129fbdd-a83b-4b2e-9c8d-ffd93c1069fd.jpeg)
![EABB98EA-35CB-4C2A-A6A6-0289F0A1773D](https://user-images.githubusercontent.com/112503137/215416508-cddf4d69-4362-4613-afa2-260d54bef05b.jpeg)

**Comment by klaasnicolaas** [comment]
Do you still have this? Because I don't experience any problems adding the integration.

**Comment by JWMass** [comment]
> Do you still have this? Because I don't experience any problems adding the integration.

resolved itself, not sure what the cause was, see below the gap in the history.

![image](https://user-images.githubusercontent.com/112503137/215747651-48e526ae-99eb-4def-afbc-560070e37467.png)

**Comment by xanderificnl** [comment]
> For those who would like to test, you can download the zip below and put the files in the custom_components folder, restart HA and then add the integration in the UI.
> 
> [easyenergy_v0.1.0.zip](https://github.com/klaasnicolaas/python-easyenergy/files/10527321/easyenergy_v0.1.0.zip)

Cheers. It's installed. 

FWIW, I'm using these to compute the full price:

```yaml
template:
  - sensor:
    - name: "EasyEnergy - Current energy price"
      unit_of_measurement: "€/kWh"
      # As of 03-02-2023 / https://www.easyenergy.com/nl/energietarieven
      state: >
        {% set minieme_opslag     = (2.178  / 100) %}
        {% set energie_belasting  = (15.245 / 100) %}
        {% set stroom_vergroening = (0.908  / 100) %}
        {% set current_hour_price = states('sensor.easyenergy_today_energy_usage_current_hour_price') | float %}

        {{ (current_hour_price + minieme_opslag + energie_belasting + stroom_vergroening) | round(6) }}
    - name: "EasyEnergy - Current gas price"
      unit_of_measurement: "€/m³"
      # As of 03-02-2023 / https://www.easyenergy.com/nl/energietarieven
      state: >
        {% set minieme_opslag     = (10.89  / 100) %}
        {% set energie_belasting  = (59.266 / 100) %}
        {% set regio_toeslag      = (1.903  / 100) %}
        {% set current_hour_price = states('sensor.easyenergy_today_gas_current_hour_price') | float %}

        {{ (current_hour_price + minieme_opslag + energie_belasting + regio_toeslag) | round(6) }}
```
